# Generated by Django 3.0.8 on 2020-07-13 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200713_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 13, 53, 46, 899461), verbose_name='date published'),
        ),
    ]
